In [6]:
import pandas as pd


trainX = pd.read_csv('./data/dengue_features_train.csv', index_col=0)
trainY = pd.read_csv('./data/dengue_labels_train.csv', index_col=0)

trainX.head()

,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
city,,,,,,,,,,,,,,,,,,,,,
sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8

In [7]:
trainX.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1456 entries, sj to iq
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   year                                   1456 non-null   int64
 1   weekofyear                             1456 non-null   int64
 2   week_start_date                        1456 non-null   object
 3   ndvi_ne                                1262 non-null   float64
 4   ndvi_nw                                1404 non-null   float64
 5   ndvi_se                                1434 non-null   float64
 6   ndvi_sw                                1434 non-null   float64
 7   precipitation_amt_mm                   1443 non-null   float64
 8   reanalysis_air_temp_k                  1446 non-null   float64
 9   reanalysis_avg_temp_k                  1446 non-null   float64
 10  reanalysis_dew_point_temp_k            1446 non-null   float64
 11  reanalysis_max_air_temp_k              1446 non-null   float64
 12  reanalysis_min_air_temp_k              1446 non-null   float64
 13  reanalysis_precip_amt_kg_per_m2        1446 non-null   float64
 14  reanalysis_relative_humidity_percent   1446 non-null   float64
 15  reanalysis_sat_precip_amt_mm           1443 non-null   float64
 16  reanalysis_specific_humidity_g_per_kg  1446 non-null   float64
 17  reanalysis_tdtr_k                      1446 non-null   float64
 18  station_avg_temp_c                     1413 non-null   float64
 19  station_diur_temp_rng_c                1413 non-null   float64
 20  station_max_temp_c                     1436 non-null   float64
 21  station_min_temp_c                     1442 non-null   float64
 22  station_precip_mm                      1434 non-null   float64
dtypes: float64(20), int64(2), object(1)
memory usage: 273.0+ KB